
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./css-codegen-backend
    container_name: backend
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=tinyllama
      - OLLAMA_LLM_LIBRARY=cpu  
      - OLLAMA_NUM_PARALLEL=1    
      - OLLAMA_CONTEXT_LENGTH=2048

  frontend:
    build: ./css-codegen-frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5050

volumes:
  ollama_data:
